apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-access-binding
  namespace: practice-nurali  # O'z namespace'ingizni kiriting
subjects:
- kind: ServiceAccount
  name: service-account  # Bu yerda foydalanuvchi nomini qo‘ying
  namespace: practice-nurali
roleRef:
  kind: Role
  name: pod-access-role
  apiGroup: rbac.authorization.k8s.io
