apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-access-role
  namespace: practice-nurali  # O'z namespace'ingizni kiriting
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list", "get", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "get"]
